export const COURSE_LIST_REQUEST = "COURSE_LIST_REQUEST";
export const COURSE_LIST_SUCCESS = "COURSE_LIST_SUCCESS";
export const COURSE_LIST_FAIL = "COURSE_LIST_FAIL";

export const SINGLE_COURSE_REQUEST = "SINGLE_COURSE_REQUEST";
export const SINGLE_COURSE_SUCCESS = "SINGLE_COURSE_SUCCESS";
export const SINGLE_COURSE_FAIL = "SINGLE_COURSE_FAIL";
