export const USER_SAVE_BASIC_INFO = "USER_SAVE_BASIC_INFO";
export const USER_SAVE_EDUCATION_INFO = "USER_SAVE_EDUCATION_INFO";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_CHECK_REQUEST = "USER_CHECK_REQUEST";
export const USER_CHECK_SUCCESS = "USER_CHECK_SUCCESS";
export const USER_CHECK_FAIL = "USER_REGISTER_FAIL";
export const USER_CHECK_RESET = "USER_REGISTER_RESET";
