export const USER_SAVE_BASIC_INFO = "USER_SAVE_BASIC_INFO";
export const USER_SAVE_EDUCATION_INFO = "USER_SAVE_EDUCATION_INFO";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
